### ISSUE TITLE
Storage back-end suggestion: WebDAV

### ISSUE THREAD

**Issue by virtadpt** [remotestorage/remotestorage.js#1093]
Are there any technical difficulties inherent in adding WebDAV to remotestorage.js as a possible storage back-end?

**Comment by skddc** [comment]
Thanks for your suggestion!

Actually, one of the reasons why the remoteStorage protocol exists, is to remedy the shortcomings of WebDAV. In fact, the protocol used WebDAV for the API part of it in the beginning and then abandoned that as well.

The main reasons (afaics) are:

* Discovery: No way to discover a storage. All settings have to be done manually by the user, and can easily be done wrong.
* CORS: Not all WebDAV servers (in fact none by default that I know of) support CORS. Without CORS, you can't connect from client-side apps in a browser. In any case, this would have to be feature-tested by the app, but secure implementations of CORS/JS intentionally don't expose information about why the CORS request failed.
* Permissions: No way to easily permit access to certain parts of a WebDAV storage, like with OAuth in RS.
* Complexity & fragmentation: Due to WebDAV's complexity, feature support and implementations vary wildly, and you basically never know what you're dealing with. And it's considerably harder to implement WebDAV server-side than it is to implement remoteStorage.

However, if a developer still thinks that this is a good idea and has benefits over RS, and also has reasonable proposals for how to remedy the aforementioned problems in this library and its [connect widget](https://github.com/remotestorage/remotestorage-widget/) add-on, I'm sure nobody's opposed to revisiting the topic. But either way, someone would have to contribute the code for this feature.

Pull requests are open, and any topic is up for debate anytime. But I'm afraid we had the WebDAV discussion multiple times in the past and nobody came up with good solutions yet. For that reason I will close this topic, but please feel free to continue the conversation, and more importantly, to create a pull-request with working code anytime!

**Comment by virtadpt** [comment]
Thank you very much - that's exactly the kind of answer that I was hoping to find!

**Comment by stokito** [comment]
Please consider to support the WebDAV. This may simplify usage.

I working on using home routers with OpenWrt into small NAS and selfhosting. Here I wrote an instruction https://openwrt.org/docs/guide-user/services/nas/webdav

As a base used Lighttpd + mod_webdav. It's performance is good and size is small.
In the same time the nodejs is simply overkill for my router. And I don't want to install something else or even compile the rs-serve.

If I'll have the WebDAV support then I can start using all the apps easily.

I also have a plan to make a custom firmware for those who want to self host from routers and home devices https://github.com/yurt-page/docs/blob/main/README.md

Now speaking about your point:

> Discovery: No way to discover a storage. All settings have to be done manually by the user

That's fine for me. A simple url like davs://user:secret@example.com/disk/ is enough. The OAuth2 redirector may be used instead of the Basic auth.

> CORS

Not a problem for the Lighttpd or I guess any other modern webservers.

> Permissions

I can easily permit an access to my folder only to my user.

> fragmentation

Let's say that only Lighttpd, Apache mod_dav and MS ISS would be supported.

**Comment by raucao** [comment]
> If I'll have the WebDAV support then I can start using all the apps easily.

Unfortunately, this would not be the case (*all the apps* that is), since app developers then still have to enable and support the WebDAV adapter, including potentially necessary UI for errors such as permissions having changed and all those other edge cases that aren't present with remoteStorage alone.

Regarding the addition of WebDAV to this library, what I wrote before is still valid:

> either way, someone would have to contribute the code for this feature

PRs are open for anyone wanting to implement this. And any and all questions about the library structure etc. will certainly be answered, both here and [on the forums](https://community.remotestorage.io/).

**Comment by DougReeder** [comment]
I will say this - if this gets implemented, there should also be a significant effort to test with as many WebDAV clients as possible. We don't want users to have a bad experience.

**Comment by stokito** [comment]
It's about WebDAV servers but not clients.
Five years passed since the ticket was created and stability of WebDAV servers and clients improved

**Comment by stokito** [comment]
Related [discussion](https://community.remotestorage.io/t/issues-with-using-webdav-as-a-back-end/797) on a forum by @DougReeder:

> It has been suggested that a WebDAV back-end would be useful (WebDAV implementations range from self-hosted to internet-scale providers). There were many reasons why remoteStorage was written as a separate protocol, not least the variations in what features various implementations of WebDAV support, and their colorful variety of bugs, which often have gone years without fixes.
> 
> However, is there a lowest common denominator of WebDAV features that could be relied on? Is there a problematic impedance mismatch?

I briefly checked the spec and it looks like the only main difference from the WebDAV is that to list a directory we need to make a [GET call to it and it will return a JSON listing](https://datatracker.ietf.org/doc/html/draft-dejong-remotestorage#page-5):

```json
{
         "@context": "http://remotestorage.io/spec/folder-description",
         "items": {
           "abc": {
             "ETag": "DEADBEEFDEADBEEFDEADBEEF",
             "Content-Type": "image/jpeg",
             "Content-Length": 82352,
             "Last-Modified": "Sat, 2 Jun 2018 15:58:23 GMT"
           },
           "def/": {
             "ETag": "1337ABCD1337ABCD1337ABCD"
           }
         }
       }
```
In the dav we need to make a PROPFIND call and in response we'll have an XML with the same data. So they are similar. Yes, the XML is slightly more difficult to parse but it's not a big deal. Another one problem is that the PROPFIND may be not supported by some http clients.
So for a server it would be great to support both directory listing methods. Then I can just mount the RS as a folder in my Ubuntu.


The Diffuse.sh player works perfectly with WebDAV and I can listen my music from it. It doesn't support the WebDAV playlist backup but hope it may be implemented in future.

**Comment by stokito** [comment]
Just found that author of the Super Productivity also was interested in the RS https://community.remotestorage.io/t/state-of-the-project/614/4

Currently the Super Productivity works with WebDAV. So at least for a widget it would be great to add the dav.

**Comment by stokito** [comment]
To summarize the RemoteStorage has three things:

1. JavaScript widget to sync data with the RS server OR Google Docs and Dropbox. I believe that we can add a support of the WebDAV here quite easily.
2. RS server implementations. They can be slightly improved and it may support the WebDAV in parallelly with the RS protocol. Then it can be used with existing WebDAV clients e.g. mounted as a folder.
3. The RS protocol itself. It's actually repeats the WebDAV in many places but has a focus on data synchronization. So the protocol may be also just reuse the WebDAV with some additional restrictions and extensions. Then A lot of code of the existing servers can be replaced with the existing WebDAV servers written in C (Lighttpd, Apache) or Go. This should make it easier to adopt but also faster and smaller.

**Comment by coderofsalvation** [comment]
Necrobumping this in 2025.
It seems WebDav is not going away anytime soon, in fact it seems to grow (nextcloud e.g.).
I'd say, that if RS wants to go where the users are (without forking an ecosystem), WebDav should be in the RS dropdown-list.
Similar like [Solid](https://community.remotestorage.io/t/adding-solid-as-a-backend/828/2), if there's even 50% feature-parity with webdav, I'd call it a win.
I would not worry too much about RS downselling Solid, or WebDav downselling RS.

**Comment by coderofsalvation** [comment]
Thank you for reaching out.
I'm a bit in a weird split regarding resources: I want to implement RS for the app I'm working on...but webdav is where my users/files are.
I need to figure out whether I can afford focusing on both.

**Comment by raucao** [comment]
FWIW, the aforementioned offer to help with any questions or problems for additional back-ends still stands, of course.

The drawbacks of WebDAV that I outlined in the first reply are also still the same. Maybe the discovery and config ones could at least be solved for ownCloud/nextCloud users, since the software is popular enough to warrant its own connect option I guess (i.e. use a WebDAV back-end under the hood, but add whatever discovery they support, and configure it specifically for that implementation).
