### ISSUE TITLE
Proposal: support websockets

### ISSUE THREAD

**Issue by jaredly** [remotestorage/remotestorage.js#1171]
This would probably require an update to the protocol, but it would be cool for servers & clients to optionally support a websocket connection, instead of the polling method currently used. It would allow for faster updates (a step toward real-time collaboration).

**Comment by skddc** [comment]
Welcome to the community, @jaredly!

In my opinion, a storage protocol like RS is not very well-suited for real-time collaboration. You can already use WebRTC/Websockets directly between collaborating peers, and then store occasional snapshots of the data in everyone's own remote storage. This concept also fits much better with the personal nature of the RS protocol, because sharing tokens for write access with other people is not really encouraged (but possible, of course).

For spec proposals, you're very welcome to open issues in https://github.com/remotestorage/spec/issues. I'm closing this one for now, as it doesn't concern the JavaScript reference client, until such an addition would be made to the protocol first.
