### ISSUE TITLE
make 'unauthorized' an event instead of an exception

### ISSUE THREAD

**Issue by michielbdejong** [remotestorage/remotestorage.js#735]
would be nice if apps that do their own widget could catch an 'unauthorized' event. Looks like right now we're doing it as an 'error' event whose event object is a special type of exception.

**Comment by skddc** [comment]
I just started implementing this for the new (external) widget, so I basically used it like an app developer would for custom UI. With discovery errors being emitted as errors with an exception object, and sync errors as well, I think catching this as an error event actually makes more sense than adding a bunch of specific events for every single error.

I'll close this issue for now, because it doesn't look like an improvement to me anymore. If someone has stronger opinions about this, and/or has a reason to add for why it should be its own event and not an error event with an error object, please feel free to re-open this issue!
