### ISSUE TITLE
Sync error after disconnect

### ISSUE THREAD

**Issue by skddc** [remotestorage/remotestorage.js#939]
There seems to be some race condition where a sync task is still scheduled and executed after disconnecting storage, but the DB is not available anymore:

![screenshot from 2016-06-21 18-35-56](https://cloud.githubusercontent.com/assets/842/16238017/2f04272e-37df-11e6-98a5-1be6122573e3.png)

It doesn't really break this app (and shouldn't break other apps). Only throws an exception after logout in some cases. We should delete all sync tasks during disconnect anyway.

**Comment by galfert** [comment]
I have seen this error again using the latest rs.js version (1.0.2).

It happened in the same integration test I described in #1117, after that issue with the undefined `sync` instance was fixed.

Looks to me like this happens when disconnecting the storage while it's still writing the results of the last sync call to IndexedDB here: https://github.com/remotestorage/remotestorage.js/blob/fa2642fa0c3c8cf6e5364e37cc20756870cadaaf/src/indexeddb.js#L187-L212

What's weird is that I tried to wrap this whole code block in a `try...catch` and still couldn't catch this exception.
