### ISSUE TITLE
Documentation Up To Date?

### ISSUE THREAD

**Issue by spencerthayer** [remotestorage/remotestorage.js#985]
Is the documentation on Google Drive and Dropbox found at  https://remotestorage.github.io/remotestorage.js/ still relevant? It seems old. If it is, where is the current documentation for Google Drive and Dropbox?

Thanks!

**Comment by skddc** [comment]
Yes, that's still relevant. However, in current stable (0.14.x) those backends are experimental and have some bugs. But we're ironing those out for the 1.0 release (e.g. [updating Dropbox to the v2 API](https://github.com/remotestorage/remotestorage.js/pull/975), for which we'll have a beta soon-ish.

The main problem with using those in the 0.14 release is if you also use the connect widget. Because the current widget isn't really made for multiple backends. The [new, seperate connect widget](https://github.com/remotestorage/remotestorage-widget) we're building for 1.0 however, is designed for choosing backends (on both desktop and mobile) from the start.

Hope this helps. I'm afraid it's taken us longer than expected to get this out the door. And it's a bit of a messy situation at the moment. But on the plus side, the whole restructuring process, new widget, and moving everything to proper JS modules will really be worth it.
